os: linux
language: minimal
services:
- docker
# DOCKER_USERNAME/DOCKER_PASSWORD have been configured in Travis CI
# env:
before_install:
- echo "Before install"
before_script:
- docker pull aesolutionssrl/marin-osm || true
script:
- docker build --pull --cache-from aesolutionssrl/marin-osm --tag aesolutionssrl/marin-osm .
- docker volume create openstreetmap-data
- docker run --rm -v openstreetmap-data:/var/lib/postgresql/12/main aesolutionssrl/marin-osm import
- docker run --rm -v openstreetmap-data:/var/lib/postgresql/12/main -p 8080:80 -d aesolutionssrl/marin-osm run
- sleep 30
- make DOCKER_IMAGE=aesolutionssrl/marin-osm stop
after_script:
- docker images
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]];
  then
  docker images ;
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ;
  docker push aesolutionssrl/marin-osm ;
  fi
notifications:
  email: true
